import DashboardHeader from "@/components/theme/Header/DashboardHeader";
import Navbar from "@/components/theme/NavBar/Navbar";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="flex justify-start items-start">
        <div className="w-0 md:w-1/5">
          <Navbar />
        </div>
        <div className="w-full md:w-4/5 ">
          <DashboardHeader />
          {children}
        </div>
      </div>
    </div>
  );
}
