import Footer from "@/components/theme/Footer/Footer";
import Header from "@/components/theme/Header/Header";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "NBTECH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex flex-col justify-between min-h-screen">
      <div>
        <Header />
        {children}
      </div>
      <Footer />
    </div>
  );
}
